FROM node:alpine

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile \
  && yarn cache clean

COPY . .
RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]
