FROM node:alpine

WORKDIR /usr/src/app
COPY package.json yarn.lock /usr/src/app
ENV YARN_CACHE_FOLDER=/dev/shm/yarn_cache
RUN yarn install --production --frozen-lockfile

COPY . .
RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]
